version: '2'
services:
  couch:
    image: "couchdb:latest"
    ports:
     - "5984:5984"
    environment:
     - COUCHDB_USER=admin
     - COUCHDB_PASSWORD=admin
    volumes:
     -  /volume1/Storage/reefstatus/data/db:/usr/local/var/lib/couchdb
     -  /volume1/Storage/reefstatus/data/log:/reefstaus/log
  nats:
    image: "nats:latest"
    ports:
         - "4222:4222"
         - "6222:6222"
         - "8222:8222"
  reefstatus:
    image: "cjburchell/reefstatus:latest"
    environment:
         - COUCHDB_ADDRESS=couch
         - COUCHDB_PORT=5984
         - PROFILUX_ADDRESS=192.168.3.10
         - PROFILUX_PORT=80
         - PROFILUX_PROTOCOL=HTTP
         - LOG_FILE_PATH=/reefstaus/log/server.log
         - LOG_CONSOLE=true
         - LOG_LEVEL=1
         - LOG_FILE=true
    ports:
     - "8082:8082"
    volumes:
      -  /volume1/Storage/reefstatus/data/log:/reefstaus/log