version: '2'
services:
  couch:
    image: "couchdb"
    ports:
     - "5984:5984"
    environment:
     - COUCHDB_USER=admin
     - COUCHDB_PASSWORD=admin
    volumes:
     - /e/data/db:/usr/local/var/lib/couchdb
  reefstatus:
    build: .
    environment:
         - COUCHDB_ADDRESS=couch
         - COUCHDB_PORT=5984
         - PROFILUX_ADDRESS=192.168.3.10
         - PROFILUX_PORT=80
         - PROFILUX_PROTOCOL=HTTP
    ports:
     - "8082:8082"